### PR TITLE
impl Hash for Method

### PR DESCRIPTION
**Pull request by wez**
This adds a Hash impl for Method.  We can't simply derive Hash
because we define `Method::NonStandard` as a case insensitive
comparison, so this PR hashes that by uppercasing the individual
characters.

The other enum variants are hashed from the result of `Method::as_str`,
which always returns the uppercase method name.

In #191 there was a request to also derive `Eq` and `PartialEq`; those
traits are already manually implemented.

I added a basic test to verify that the hash and comparison for
`NonStandard` are case-insensitive.

closes: https://github.com/tiny-http/tiny-http/issues/191

### CODE REVIEW

**Review by rawler — APPROVED** [review]
LGTM

**Review by rawler — CHANGES_REQUESTED** [review]
After some thought, I had a glance at the HTTP RFC:

>      request-line   = method SP request-target SP HTTP-version CRLF
> 
>    The method token indicates the request method to be performed on the
>    target resource.  The request method is case-sensitive.
> 
>      method         = token
> 
It seems `PartialEq` is currently breaking spec by comparing case-insensitive, and without that there is no need to normalise case for `Hash`.

Would you like to fix this for both PartialEq and Hash?

**Comment by wez** [comment]
OK, I've removed the case insensitive impls and now `Method` derives `PartialEq`, `Eq` and `Hash`.

**Review by rawler — APPROVED** [review]

**Comment by rawler** [comment]
Awesome, Thank you!

I'm not one of the regular maintainers, they seem to be a bit swamped ATM, but I have commit rights at least. I'm happy with with, but I'll let this sit for a while for a regular maintainer to have a chance to weigh in, before merging.

**Comment by bradfier** [comment]
Thanks for submitting this, and @rawler for the review. Sorry that it has sat still for so long, can you rebase the PR and we'll get it moving again?

**Comment by bradfier** [comment]
Thanks!

**Pull request merged**
