### PR TITLE
Add unblock method for graceful shutdown

### PR DESCRIPTION
**Pull request by rawler**

### CODE REVIEW

**Comment by rawler** [comment]
Replaces https://github.com/tiny-http/tiny-http/pull/156

**Comment by rawler** [comment]
This change was already accepted in #156. I'll give it a few days, and then merge unless there are objections.

**Comment by tamird** [comment]
This unblocks the server, but doesn't prevent the thread pool from leaking. In other words, it doesn't solve what https://github.com/tomaka/rouille/pull/219 attempts to solve.

**Comment by rawler** [comment]
@tamird From what I can tell, these two PR:s are distinct, but possibly complementary.

This PR, or an PR in tiny-http naturally, cannot wait for threads used to handle requests, since those threads are completely outside it's control?

However, this PR could provide for a simple replacement of the functionality seen in https://github.com/tomaka/rouille/blob/a72ebf1250049cf9ac46919ef16984b056263d03/src/lib.rs#L438 and would fit in between 2 and 3 in the graceful shutdown procedure outlined in https://github.com/tomaka/rouille/pull/219/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759L438. (Stop receiver and make sure new clients can't be queued)

**Pull request merged**
