### PR TITLE
Allow constructing the server from TcpListener

### LINKED ISSUE #164: Optionally accept TCPListener rather than ToSocketAddrs
With `TCPListener` it's possible to [`listenfd`](https://github.com/mitsuhiko/rust-listenfd) and socket activation from systemd.

This allows to hide services into network namespaces and disallow them to do `bind` and `listen`, which is very handy security-wise. Not only can one disallow these, it's also probably possible to use `RestrictAddressFamilies` and disable even `AF_INET` and `AF_INET6` for even more through lockdown.

I'm not really sure how to make this work without breaking backward compatibility or introducing something like `_with_listener` variants for methods that require `ToSocketAddrs` today.

### PR DESCRIPTION
**Pull request by Kixunil**
This allows constructing the server from an externally obtained TCP
listener such as using systemd.

Closes #164

### CODE REVIEW

**Comment by bradfier** [comment]
Thanks for the PR! Can you rebase it and we'll get it moving again?

**Comment by Kixunil** [comment]
Done.

**Comment by bradfier** [comment]
Thanks!

**Comment by Kixunil** [comment]
Thank you too! Any eta on the new release?

**Comment by bradfier** [comment]
There should be a `0.9.0` within a day or so, there's a potentially breaking changing in how we handle case in HTTP request methods so it has to be a full version increment.

**Pull request merged**
