### PR TITLE
add support for unix domain sockets

### PR DESCRIPTION
**Pull request by njaard**
with my "anysocket" crate

Implements #172

### CODE REVIEW

**Review by rawler — COMMENTED** [review]
Not familiar enough with the code to approve, but the PR looks straight-forward enough. I think a test, testing actual unix-socket functionality is in order though.

**Comment by tomaka** [comment]
I would personally be against this type of change, as it strongly looks like a feature creep to me.
If someone needs Unix domain sockets, there exist other libraries than `tiny-http`.

**Comment by njaard** [comment]
@tomaka Unix Domain sockets are an essential part of the socket world. They're important for hosting via reverse proxies

**Comment by rawler** [comment]
Hi. Thank you for the PR.

While I'm myself on the fence on the value of http-servers on unix sockets, it's importance is demonstrated by the fact that _two_ PR:s have been devised for this.

However of the two approaches, considering `anysocket` seems to be a one-man effort, at 0.1 release, and with no other dependent crates, I'd strongly avoid adding that as a dependency for tiny-http. I'm therefore going to close this PR.

If you still want to contribute, since you're obviously knowledgeable in the field, I'd value your input on https://github.com/tiny-http/tiny-http/pull/187.

**Pull request closed without merging**
